IMAGING_ANATOMY_LIST = [
    "CT head: non-contrast axial",
    "CT head: non-contrast axial (2)",
    "CT head: non-contrast coronal",
    "CT head: non-contrast sagittal",
    "CT head: non-contrast axial with clinical questions",
    "CT head: angiogram axial",
    "CT head: angiogram coronal",
    "CT head: angiogram sagittal",
    "CT head: venogram axial",
    "CT head: venogram coronal",
    "CT head: venogram sagittal",
    "CT head: venogram sagittal (diagram)",
    "Brain anatomy MRI",
    "MR head: T1 axial (non-contrast)",
    "MR head: T2 axial (non-contrast)",
    "MR head: T1 sagittal (non-contrast)",
    "MR head: T2 sagittal (non-contrast)",
    "MR head: T1 coronal (non-contrast)",
    "MR head: T2 coronal (non-contrast)",
    "MR head: T1 axial (contrast)",
    "MR head: T1 sagittal (contrast)",
    "MR head: T1 coronal (contrast)",
    "MR head: TOF angiogram axial",
    "MR head: TOF venogram axial",
    "MR head: angiogram of choroidal arteries",
    "MR pituitary: T1 post gad sagittal",
    "MR pituitary: T1 post gad coronal",
    "MR pituitary: T2 sagittal",
    "cerebral angiogram (DSA): lateral",
    "cerebral angiogram (DSA): frontal",
    "CT head: bone window axial skull base",
    "CT head: bone window axial calvarium",
    "CT facial bones/orbits: axial",
    "CT facial bones/orbits: coronal",
    "CT facial bones/orbits: sagittal",
    "CT sinuses: coronal, axial and sagittal",
    "CT sinuses: axial",
    "CT temporal bone: axial",
    "CT temporal bone: coronal",
    "CT temporal bone: sagittal",
    "CT temporal bones: multiplanar",
    "CT temporal bone facial nerve: axial",
    "CT temporal bone inner ear: axial",
    "CT temporal bone middle ear: axial",
    "CT temporal bone external ear: axial",
    "CT temporal bone: axial",
    "CT neck: arterial axial",
    "CT neck: arterial coronal",
    "CT neck: arterial sagittal",
    "CT neck: axial, coronal and sagittal",
    "CT neck lymph node levels: axial, coronal, sagittal",
    "MR IAMs: axial",
    "MR IAMs: coronal",
    "MR IAMs: sagittal",
    "MR neck spaces: axial",
    "MR neck: oral cavity coronal",
    "MR temporomandibular joint: sagittal",
    "MR brachial plexus: sagittal and coronal",
    "Orthopantomography (OPG): dental",
    "Orthopantomography (OPG): non dental",
    "Dental anatomy (zoomed-in OPG)",
    "Branches of external carotid artery (DSA)",
    "X-ray cervical spine: lateral",
    "X-ray cervical spine: AP",
    "X-ray cervical spine: open-mouth peg",
    "X-ray thoracic spine: frontal and lateral",
    "X-ray lumbar spine: oblique",
    "X-ray sacrum: frontal",
    "CT cervical spine: bone window axial",
    "CT cervical spine: bone window sagittal",
    "CT cervical spine: bone window coronal",
    "CT thoracic spine: bone window axial",
    "CT thoracic spine: bone window sagittal",
    "CT thoracic spine: bone window coronal",
    "CT lumbar spine: bone window axial",
    "CT lumbar spine: bone window sagittal",
    "CT lumbar spine: bone window coronal",
    "MR cervical spine: T2 axial",
    "MR cervical spine: T2 sagittal",
    "MR cervical spine: T2 sagittal (ligaments)",
    "MR cervical spine: Brachial plexus anatomy",
    "MR thoracic spine: T2 axial",
    "MR thoracic spine: T2 sagittal",
    "MR lumbar spine: T2 axial",
    "MR lumbar spine: T2 sagittal",
    "CXR: lungs and fissures",
    "CXR: mediastinum",
    "CT chest: arterial axial",
    "CT chest: arterial coronal",
    "CT chest: arterial sagittal",
    "CT chest: lymph node stations axial",
    "CT chest: mediastinal compartments",
    "CT chest: lung window axial",
    "CT chest: lung window coronal",
    "CT chest: lung window sagittal",
    "CT chest: bronchopulmonary segments axial",
    "CT chest: bronchi axial",
    "CT coronary arteries: arterial axial",
    "Coronary angiogram (DSA)",
    "AXR: organs",
    "AXR: bowel",
    "AXR: large bowel",
    "X-ray pelvis: AP",
    "CT abdomen/pelvis (upper): portal venous axial",
    "CT abdomen/pelvis (lower): portal venous axial",
    "CT abdomen/pelvis: portal venous coronal",
    "CT abdomen/pelvis: portal venous sagittal",
    "CT abdomen/pelvis: arterial axial",
    "CT abdomen/pelvis: arterial coronal",
    "CT abdomen/pelvis: arterial sagittal",
    "CT abdomen hepatic segments: axial",
    "CT Abdomen: Portal vein anatomy",
    "CT abdomen/pelvis: delayed (urogram) axial",
    "CT abdomen/pelvis: delayed (urogram) coronal",
    "CT abdomen/pelvis: delayed (urogram) sagittal",
    "MRCP: axial",
    "MRCP: coronal",
    "MR prostate",
    "DSA aorta",
    "DSA hepatic artery",
    "DSA splenic artery",
    "DSA superior mesenteric artery",
    "DSA inferior mesenteric artery",
    "DSA internal iliac artery",
    "US female pelvis (transabdominal)",
    "X-ray shoulder: frontal (IR and ER), Y-lateral and axial views",
    "X-ray clavicle: frontal and oblique",
    "X-ray humerus: frontal and lateral",
    "X-ray elbow: frontal, lateral and oblique",
    "X-ray elbow: frontal and lateral",
    "X-ray elbow: frontal and lateral",
    "X-ray forearm: frontal and lateral",
    "X-ray wrist: frontal, lateral, oblique",
    "X-ray wrist: frontal and lateral",
    "X-ray wrist: frontal",
    "X-ray wrist: carpal tunnel",
    "X-ray wrist: carpals only",
    "X-ray hand: frontal, oblique and lateral",
    "X-ray hand: frontal and oblique",
    "X-ray hand: frontal and lateral figures",
    "Ultrasound shoulder: oblique",
    "Ultrasound shoulder: rotator cuff",
    "Ultrasound forearm: nerve anatomy",
    "CT shoulder: axial",
    "CT shoulder: sagittal",
    "CT shoulder: coronal",
    "CT elbow: axial",
    "CT elbow: sagittal",
    "CT elbow: coronal",
    "CT wrist: axial",
    "CT wrist: sagittal",
    "CT wrist: coronal",
    "MRI shoulder: axial",
    "MRI shoulder: sagittal",
    "MRI shoulder: coronal",
    "MRI elbow: axial",
    "MRI elbow: sagittal",
    "MRI elbow: coronal",
    "MRI wrist: Wrist tendons - topographic anatomy",
    "MRI wrist: axial",
    "MRI wrist: sagittal",
    "MRI wrist: coronal",
    "MRI hand: axial",
    "MRI hand: sagittal",
    "MRI hand: coronal",
    "X-ray pelvis: frontal",
    "X-ray pelvis: frontal",
    "X-ray pelvis: iliac oblique",
    "X-ray pelvis: obturator oblique",
    "X-ray hip: frontal and lateral",
    "X-ray hip: frontal acetabulum",
    "X-ray femur: frontal and lateral",
    "X-ray knee: frontal, lateral and skyline",
    "X-ray knee: frontal and lateral",
    "X-ray knee: frontal, lateral and skyline",
    "X-ray knee: skyline",
    "X-ray tibia/fibula: frontal and lateral",
    "X-ray ankle: frontal, mortise and lateral",
    "X-ray ankle: frontal and lateral",
    "X-ray calcaneal: axial",
    "X-ray foot: frontal, oblique and lateral",
    "X-ray foot: frontal",
    "X-ray foot: ossicles",
    "Ultrasound of the neonatal hip",
    "CT hip: axial",
    "CT hip: sagittal",
    "CT hip: coronal",
    "CT knee: axial",
    "CT knee: sagittal",
    "CT knee: coronal",
    "CT foot and ankle: axial",
    "CT foot and ankle: sagittal",
    "CT foot and ankle: coronal",
    "MRI hip: axial",
    "MRI hip: sagittal",
    "MRI hip: coronal",
    "MRI Thigh muscles: cross sectional anatomy",
    "MRI knee: axial, sagittal and coronal",
    "MRI anatomy of ankle",
    "Ankle tendons: topographic anatomy",
    "MRI ankle: sagittal",
    "MRI ankle: coronal",
    "MRI foot: axial",
    "MRI foot: sagittal",
    "MRI foot: coronal",
]